all:
  .ys_jquery_revolutions_plugins:
    ### To load jQuery from ajax.googleapis.com:
    ### - jquery.min.js
    #ys_jquery_path: http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js
    ### - jquery.js
    #ys_jquery_path: http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js

    ### To load jQuery from localhost
    ### - Only available jquery.min.js
    ys_jquery_path:   /ysJQueryRevolutionsPlugin/js/jquery/jquery-1.3.2.min.js
    ys_jquery_css:    /ysJQueryRevolutionsPlugin/css
    ys_jquery_images: /ysJQueryRevolutionsPlugin/images
    ys_jquery_plugins_folder: /ysJQueryRevolutionsPlugin/js/jquery/plugins

    plugins:
      auto_complete:
        js_files:
        css_files:
